// <auto-generated />
using System;
using HalloWinUI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalloWinUI.Data.Migrations
{
    [DbContext(typeof(HalloWinUIDbContext))]
    [Migration("20251210033605_MigrationInitiale")]
    partial class MigrationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HalloWinUI.Data.Models.Bonbon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categorie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaisonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaisonId");

                    b.ToTable("Bonbons");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Enfant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enfants");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Maison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSignalee")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maisons");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Visite", b =>
                {
                    b.Property<int>("EnfantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaisonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateVisite")
                        .HasColumnType("TEXT");

                    b.HasKey("EnfantId", "MaisonId", "DateVisite");

                    b.HasIndex("MaisonId");

                    b.ToTable("Visites");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Bonbon", b =>
                {
                    b.HasOne("HalloWinUI.Data.Models.Maison", "Maison")
                        .WithMany("Bonbons")
                        .HasForeignKey("MaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maison");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Visite", b =>
                {
                    b.HasOne("HalloWinUI.Data.Models.Enfant", "Enfant")
                        .WithMany("Visites")
                        .HasForeignKey("EnfantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HalloWinUI.Data.Models.Maison", "Maison")
                        .WithMany("Visites")
                        .HasForeignKey("MaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfant");

                    b.Navigation("Maison");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Enfant", b =>
                {
                    b.Navigation("Visites");
                });

            modelBuilder.Entity("HalloWinUI.Data.Models.Maison", b =>
                {
                    b.Navigation("Bonbons");

                    b.Navigation("Visites");
                });
#pragma warning restore 612, 618
        }
    }
}
